# -*- coding: utf-8 -*-
"""[카카오 부트캠프] 과제 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VhxCfNpjIEwN7wjPSgTS1JWPFpbL-ukO

#1. NumPy 배열 생성 및 연산
"""

# - NumPy를 사용해 3x3 정수 배열(1부터 9까지)과 2x5 실수 배열(0~1 사이 난수)을 생성하세요.
# 생성한 배열의 합계와 평균을 각각 계산하고, 두 배열을 곱한 결과를 출력하세요.
# - - 배열의 형태를 유지하지 않아도 괜찮습니다.

import numpy as np

a = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
             )
b = np.random.rand(2, 5)
# 그냥 곱을하면 형태가 안맞기에 오류가 발생
# 평탄화 : a와 b의 요소수가 다르기 떄문에 평탄화도 안된다
# 차원 추가 : b의 형태를 조정하여 a와 곱셈을 수행할수 있다?
# 배열의 형태를 유지하지 않아도 된다 -> 배열을 구성하는 원소개수가 달라져도 된다
b_reshaped1 = b.transpose() # b 전치
b_reshaped2 = b_reshaped1[:3,:2]
a_reshaped = a[:2,:3]
a_reshaped = a_reshaped.T #a의 전치

print("a의 합계:", np.sum(a))
print("a의 평균:", np.mean(a))
print("b의 합계:", np.sum(b))
print("b의 평균:", np.mean(b))
print("a 와 b의 곱셈:", a_reshaped * b_reshaped2)

"""# 2. Pandas를 활용한 데이터 처리"""

# - 아래 데이터를 DataFrame으로 생성하세요.

# Name: [Alice, Bob, None, Charlie]
# Age: [25, None, 28, 35]
# City: [New York, None, Chicago, None]

# - 누락된 이름은 "Unknown"으로, 나이는 평균 나이로 채우고 수정된 DataFrame을 출력하세요.

import pandas as pd

df =pd.DataFrame({
    'Name' : ['Alice', 'Bob', None, 'Charlie'],
    'Age' : [25, None, 28, 35],
    'City' : ['New York' , None, 'Chicago', None]
})

df['Name'] = df['Name'].fillna('Unknown')
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['City'] = df['City'].fillna('Unknown')
df

"""# 3: HTTP 통신을 활용한 데이터 읽기 및 저장"""

# - https://jsonplaceholder.typicode.com/todos 에서 JSON 데이터를 가져오세요.
# 데이터를 파일로 저장한 뒤, "title" 키의 값을 출력하세요.

import pandas as pd

data = pd.read_json("https://jsonplaceholder.typicode.com/todos")

new_df = data.to_csv("todos.csv")
new_df = pd.read_csv("todos.csv",index_col=0)
new_df['title']